"""Canonical MediaFlow Pro domain model."""

from .audio import (
    AudioBus,
    AudioEffect,
)
from .downloads import DownloadEntry, DownloadPlan, DownloadRequest
from .enums import (
    AssetKind,
    AssetOrigin,
    AssetStatus,
    AudioEffectKind,
    ClipMediaKind,
    ColorMode,
    ExportFormat,
    SequenceKind,
    TaskKind,
    TaskStatus,
    TrackKind,
    TransitionKind,
)
from .exports import ExportPreset
from .highlights import HighlightCandidate
from .model_base import (
    DomainModel,
    new_id,
    now_ms,
)
from .progress import OperationProgress
from .project import (
    Asset,
    AssetFingerprint,
    MediaMetadata,
    Project,
    ProjectProfile,
    Sequence,
    SequenceInOut,
)
from .project_records import (
    ExportHistoryRecord,
    ExportQualityCheck,
    ExportQualityReport,
    ProjectVersionRecord,
)
from .sequence_bounds import SequenceBoundaryAnalysis
from .subtitles import (
    SubtitleDocument,
    SubtitlePlacement,
    SubtitleSegment,
    SubtitleWord,
)
from .tasks import Task
from .timeline import (
    Clip,
    ClipAudio,
    ClipTransform,
    ClipTransformKeyframe,
    CompoundClip,
    TimelineMarker,
    TimelineRange,
    TimelineState,
    Track,
    Transition,
)
from .transcript_edits import (
    TranscriptEditImpact,
    TranscriptEditPlan,
    TranscriptEditRequest,
    TranscriptEditResult,
    TranscriptEditSelection,
    TranscriptFrameInterval,
    TranscriptResolvedSelection,
    TranscriptSegmentSnapshot,
    TranscriptSnapshot,
)
from .web_media import (
    EditableMediaManifest,
    WebAnimationTrack,
    WebAssetSpec,
    WebCanvas,
    WebClipExportResult,
    WebClipState,
    WebComponentMetadata,
    WebDataField,
    WebDataSnapshot,
    WebEasing,
    WebFieldConstraint,
    WebKeyframe,
    WebLayerBounds,
    WebLayerManifest,
    WebLayerOverride,
    WebLayout,
    WebRebindReport,
    WebStateDiff,
    WebThemeVariable,
    WebTimeline,
    WebVariantResult,
)

__all__ = [
    "AssetKind",
    "AssetOrigin",
    "AssetStatus",
    "AudioEffectKind",
    "ClipMediaKind",
    "ColorMode",
    "ExportFormat",
    "SequenceKind",
    "TaskKind",
    "TaskStatus",
    "TrackKind",
    "TransitionKind",
    "DownloadEntry",
    "DownloadPlan",
    "DownloadRequest",
    "SequenceBoundaryAnalysis",
    "Asset",
    "AssetFingerprint",
    "AudioBus",
    "AudioEffect",
    "Clip",
    "ClipAudio",
    "ClipTransform",
    "ClipTransformKeyframe",
    "CompoundClip",
    "DomainModel",
    "ExportPreset",
    "ExportHistoryRecord",
    "ExportQualityCheck",
    "ExportQualityReport",
    "HighlightCandidate",
    "MediaMetadata",
    "Project",
    "ProjectProfile",
    "ProjectVersionRecord",
    "OperationProgress",
    "Sequence",
    "SequenceInOut",
    "SubtitleDocument",
    "SubtitlePlacement",
    "SubtitleSegment",
    "SubtitleWord",
    "Task",
    "TimelineState",
    "TimelineMarker",
    "TimelineRange",
    "Track",
    "Transition",
    "TranscriptEditImpact",
    "TranscriptEditPlan",
    "TranscriptEditRequest",
    "TranscriptEditResult",
    "TranscriptEditSelection",
    "TranscriptFrameInterval",
    "TranscriptResolvedSelection",
    "TranscriptSegmentSnapshot",
    "TranscriptSnapshot",
    "EditableMediaManifest",
    "WebAnimationTrack",
    "WebAssetSpec",
    "WebCanvas",
    "WebClipExportResult",
    "WebClipState",
    "WebComponentMetadata",
    "WebDataField",
    "WebDataSnapshot",
    "WebEasing",
    "WebFieldConstraint",
    "WebKeyframe",
    "WebLayout",
    "WebLayerBounds",
    "WebLayerManifest",
    "WebLayerOverride",
    "WebRebindReport",
    "WebStateDiff",
    "WebThemeVariable",
    "WebTimeline",
    "WebVariantResult",
    "new_id",
    "now_ms",
]
