from __future__ import annotations

import re
import stat
import time
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit

from mediaflow.atomic_file import atomic_write_text


class CookieStore:
    """Persist browser cookies per media domain in yt-dlp's Netscape format."""

    MAX_AGE_SECONDS = 24 * 60 * 60

    def __init__(self, directory: str | Path):
        self.directory = Path(directory).resolve()

    def save(self, domain: str, cookies: list[dict[str, Any]]) -> Path:
        normalized = self.normalize_domain(domain)
        if not cookies:
            raise ValueError("没有可保存的 Cookie")
        lines = ["# Netscape HTTP Cookie File", "# Generated by MediaFlow Pro"]
        for cookie in cookies:
            name = str(cookie.get("name") or "").strip()
            value = str(cookie.get("value") or "")
            if not name or not value:
                continue
            cookie_domain = self.normalize_domain(str(cookie.get("domain") or normalized))
            include_subdomains = str(cookie.get("domain") or "").startswith(".")
            path = str(cookie.get("path") or "/")
            secure = "TRUE" if bool(cookie.get("secure")) else "FALSE"
            expires = cookie.get("expirationDate", cookie.get("expires"))
            try:
                expiration = int(float(expires)) if expires is not None else 0
            except (TypeError, ValueError):
                expiration = 0
            if expiration <= 0:
                expiration = 0
            elif expiration <= int(time.time()):
                continue
            lines.append(
                "\t".join(
                    (
                        f".{cookie_domain}" if include_subdomains else cookie_domain,
                        "TRUE" if include_subdomains else "FALSE",
                        path,
                        secure,
                        str(expiration),
                        name,
                        value,
                    )
                )
            )
        if len(lines) == 2:
            raise ValueError("Cookie 数据中没有可用条目，可能已过期或缺少名称和值")
        self.directory.mkdir(parents=True, exist_ok=True)
        destination = self.path_for_domain(normalized)
        atomic_write_text(destination, "\n".join(lines) + "\n")
        return destination

    def status(self, domain: str) -> dict[str, Any]:
        normalized = self.normalize_domain(domain)
        path = self.path_for_domain(normalized)
        try:
            source_stat = path.stat()
            exists = stat.S_ISREG(source_stat.st_mode) and source_stat.st_size > 0
        except OSError:
            source_stat = None
            exists = False
        age_seconds = (
            max(0.0, time.time() - source_stat.st_mtime)
            if exists and source_stat is not None
            else 0.0
        )
        return {
            "domain": normalized,
            "path": str(path) if exists else "",
            "exists": exists,
            "valid": (
                exists
                and age_seconds <= self.MAX_AGE_SECONDS
                and self._has_current_cookie(path)
            ),
            "ageHours": round(age_seconds / 3_600, 1) if exists else 0.0,
        }

    def clear(self, domain: str) -> bool:
        path = self.path_for_domain(domain)
        if not path.is_file():
            return False
        path.unlink()
        return True

    def resolve_for_url(self, url: str) -> Path | None:
        host = (urlsplit(url).hostname or "").lower()
        if not host:
            return None
        labels = host.split(".")
        candidates = [
            ".".join(labels[index:])
            for index in range(max(1, len(labels) - 1))
        ]
        if any(domain in {"x.com", "twitter.com"} for domain in candidates):
            candidates.extend(("x.com", "twitter.com"))
        for domain in dict.fromkeys(candidates):
            status = self.status(domain)
            if status["valid"]:
                return Path(status["path"])
        return None

    def path_for_domain(self, domain: str) -> Path:
        return self.directory / f"{self.normalize_domain(domain)}.txt"

    @staticmethod
    def _has_current_cookie(path: Path) -> bool:
        now = int(time.time())
        try:
            lines = path.read_text(encoding="utf-8").splitlines()
        except (OSError, UnicodeError):
            return False
        for line in lines:
            if not line or line.startswith("#"):
                continue
            fields = line.split("\t")
            if len(fields) != 7:
                continue
            try:
                expiration = int(fields[4])
            except ValueError:
                continue
            if fields[5] and fields[6] and (expiration == 0 or expiration > now):
                return True
        return False

    @staticmethod
    def normalize_domain(domain: str) -> str:
        value = domain.strip().lower()
        if "://" in value:
            value = urlsplit(value).hostname or ""
        value = value.lstrip(".")
        if value.startswith("www."):
            value = value[4:]
        if not value or not re.fullmatch(r"[a-z0-9.-]+", value):
            raise ValueError("Cookie 域名无效")
        return value
